apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec: 
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      db: mysql
      tier: db
  strategy:
    type: Recreate 

  template: 
    metadata: 
      labels: 
        db: mysql
        tier: db
    spec: 
      volumes:
        - name: mysql-init-db
          configMap:
            name: mysql-initdb-config

        - name: mysql-data
          emptyDir: {}
          
      containers:
        - name: mysql-cont
          image: mysql:8.0
          imagePullPolicy: IfNotPresent

          ports:
            - name: mysql
              containerPort: 3306
          
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD 

            - name: MYSQL_HEALTHCHECK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_HEALTHCHECK_PASSWORD

            - name: MYSQL_HEALTHCHECK_USER
              value: healthcheck

          volumeMounts:
            - name: mysql-init-db
              mountPath: /docker-entrypoint-initdb.d
              # subPath: init.sql  # Mount only init.sql, not the entire ConfigMap

            - name: mysql-data
              mountPath: /var/lib/mysql
            
          

          


            
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    db: mysql
spec:
  #type: ClusterIP
  clusterIP: None # This means we are going to use Pod IP directly
  selector:
    db: mysql
    tier: db
  ports:
  - name: mysqldb-port
    protocol: "TCP"
    port: 3306           # Service port
    targetPort: 3306     # Container port
